server:
  error:
    include-message: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/barbearia?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

